/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.CultivoController;
import Controlador.ProduccionController;
import Enum.EstadoCrecimiento;
import Enum.Rol;
import Enum.TipoCultivo;
import Modelo.CultivoDTO;
import Modelo.ProduccionDTO;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AsusVivobook
 */
public class FrmListaCultivo extends javax.swing.JFrame {
private CultivoController controller;
    private String username;
    private Rol rol;

    public FrmListaCultivo(String username, Rol rol) {
        this();
        this.username = username;
        this.rol = rol;
    }

    public FrmListaCultivo() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Lista de Cultivos Registrados");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        try {
            controller = new CultivoController();
            cargarTabla();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error de conexión: " + ex.getMessage());
        }

        // Doble clic para editar
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    int fila = jTable1.getSelectedRow();
                    if (fila != -1) {
                        abrirFormularioEdicion(fila);
                    }
                }
            }
        });
    }

  private void cargarTabla() {
  try {
            List<CultivoDTO> lista = controller.listarCultivos(null); 

            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(new String[]{
                "Id", "Nombre", "Área Sembrada", "Fecha Siembra", "Fecha Cosecha", "Tipo", "Estado"
            });

            if (lista == null || lista.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay cultivos registrados aún.", "Información", JOptionPane.INFORMATION_MESSAGE);
            } else {
                for (CultivoDTO dto : lista) {
                    modelo.addRow(new Object[]{
                        dto.getId(),
                        dto.getNombre(),
                        dto.getAreaSembrada(),
                        dto.getFechaSiembra() != null ? dto.getFechaSiembra().toString() : "",
                        dto.getFechaCosecha() != null ? dto.getFechaCosecha().toString() : "",
                        dto.getTipo().name(),
                        dto.getEstadoCrecimiento().name()
                    });
                }
            }

            jTable1.setModel(modelo);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, 
                "Error al cargar cultivos:\n" + e.toString(), 
                "Error", JOptionPane.ERROR_MESSAGE);
        }
}

    private void abrirFormularioEdicion(int fila) {
        try {
            CultivoDTO dto = new CultivoDTO();

            dto.setId((Integer) jTable1.getValueAt(fila, 0));
            dto.setNombre((String) jTable1.getValueAt(fila, 1));
            dto.setAreaSembrada(Double.parseDouble(jTable1.getValueAt(fila, 2).toString()));

            String fechaSiembra = jTable1.getValueAt(fila, 3).toString();
            dto.setFechaSiembra(fechaSiembra.isEmpty() ? null : java.sql.Date.valueOf(fechaSiembra));

            Object fechaCosechaObj = jTable1.getValueAt(fila, 4);
            String fechaCosecha = (fechaCosechaObj != null) ? fechaCosechaObj.toString() : null;
            dto.setFechaCosecha((fechaCosecha != null && !fechaCosecha.isEmpty()) ? java.sql.Date.valueOf(fechaCosecha) : null);

            dto.setTipo(TipoCultivo.valueOf(jTable1.getValueAt(fila, 5).toString()));
            dto.setEstadoCrecimiento(EstadoCrecimiento.valueOf(jTable1.getValueAt(fila, 6).toString()));

            // Abrir el formulario principal y cargar los datos
            FrmCultivo form = new FrmCultivo(username, rol);
            form.cargarDesdeTabla(dto);
            form.setVisible(true);
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al abrir el registro: " + e.getMessage());
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jTable1.setBackground(new java.awt.Color(204, 255, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Area Sembrada", "Fecha Siembra", "Fecha Cosecha", "Tipo", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmListaCultivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmListaCultivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmListaCultivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmListaCultivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmListaCultivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
