/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.UsuarioController;
import Enum.Rol;
import Modelo.UsuarioDTO;
import java.util.List;
import javax.swing.JOptionPane;
import Modelo.Usuario;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AsusVivobook
 */
public class FrmListaUsuario extends javax.swing.JFrame {
private UsuarioController controller;
private String username;
private Rol rol;


public FrmListaUsuario(String username, Rol rol) {
    this();
    this.username = username;
    this.rol = rol;
}

public FrmListaUsuario() {
    initComponents();
    this.setLocationRelativeTo(null);
    this.setTitle("Lista de Usuarios del Sistema");
 
    try {
        controller = new UsuarioController();
        cargarDesdeTabla();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al cargar usuarios: " + ex.getMessage());
    }
    

    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
    });
}


private void cargarDesdeTabla() {
    try {
     
        UsuarioController uc = new UsuarioController();
        List<UsuarioDTO> lista = uc.listarUsuario(); 

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[]{
            "ID", "Usuario", "Contraseña (Hash)", "Rol", "Activo"
        });

       
       for (UsuarioDTO dto : lista) {
    modelo.addRow(new Object[]{
       
        String.valueOf(dto.getId()), 
        dto.getUsername(),
        "******", // Contraseña
        dto.getRol().name(),
      
        dto.isActivo() ? "Activo" : "Inactivo"
    });
}
     

        jTable1.setModel(modelo);
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar la lista: " + e.getMessage());
    }
}


private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
    if (evt.getClickCount() == 2) { 
        int fila = jTable1.getSelectedRow();
        if (fila == -1) return;

        try {
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            String usernameSeleccionado = (String) modelo.getValueAt(fila, 1);
        
            UsuarioController uc = new UsuarioController();
            UsuarioDTO dto = uc.buscarPorUsername(usernameSeleccionado); 
            
            if (dto != null) {
             
                FrmUsuario formGestion = new FrmUsuario();
                formGestion.cargarDesdeTabla(dto); 
                
                formGestion.setVisible(true);
                this.dispose(); 
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al abrir para edición: " + e.getMessage());
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Usuario", "Contraseña", "Rol", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmListaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmListaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmListaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmListaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmListaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
