/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ProduccionController;
import DAO.CultivoDAO;
import DB.ConnectionFactory;
import Enum.Rol;
import Modelo.ProduccionDTO;
import Vista.FrmInicio;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.Date;
import Enum.Destino;
import Modelo.Cultivo;
import Modelo.CultivoDTO;
import java.util.List;
import java.sql.Connection;
/**
 *
 * @author AsusVivobook
 */
public class FrmProduccion extends javax.swing.JFrame {
      private ProduccionController controller;
      private String username; 
      private Rol rol;

    /**
     * Creates new form FrmProduccion
     */
   public FrmProduccion(String username, Rol rol) {
        this(); 
       this.username = username;
        this.rol = rol;
        aplicarPermisos();
        cargarCultivosCombo();
     }
     
    public FrmProduccion() { 
      initComponents();
     setLocationRelativeTo(null);

      try {
     controller = new ProduccionController();
     } catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, "Error al conectar: " + ex.getMessage());
    }
       CargarBolas();
    }
     private void CargarBolas() {
    jComboBox1.removeAllItems();
    for (Destino  destino : Destino.values()) {
        jComboBox1.addItem(destino.name());
    }
    
     }
  private void cargarCultivosCombo() {
    try {
        Connection conn = new ConnectionFactory().getConnection();
        CultivoDAO dao = new CultivoDAO(conn);

        List<Cultivo> lista = dao.listar("");

        ComboCultivo.removeAllItems();

        for (Cultivo c : lista) {
            ComboCultivo.addItem(c.getId() + " - " + c.getNombre());
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error cargando cultivos: " + e.getMessage());
    }
}

     
     public void cargarDesdeTabla(Modelo.ProduccionDTO dto) {
    jTextField1.setText(String.valueOf(dto.getId())); 
    jFormattedTextField1.setText(dto.getFecha() != null ? dto.getFecha().toString() : ""); 

    jTextField2.setText(String.valueOf(dto.getCantidadRecolectada())); 
    jTextField4.setText(dto.getCalidad()); 
    
    jComboBox1.setSelectedItem(dto.getDestino()); 

}
     private void aplicarPermisos() {
    if (this.rol == Rol.TRABAJADOR) {

        btnagregar.setEnabled(false);
        btnactualizar.setEnabled(false);
        btneliminar.setEnabled(false);

       
        btnlistarporFecha.setEnabled(true);  
        btnVerTabla.setEnabled(true);
        btnSalir.setEnabled(true);

       
}
}
    private void limpiarCampos() {
    jTextField1.setText("");
    jFormattedTextField1.setText("");
    jTextField2.setText("");
    jTextField4.setText("");
    ComboCultivo.setSelectedIndex(0);
    jComboBox1.setSelectedIndex(0);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnagregar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnlistarporFecha = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        btnVerTabla = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtCultivo = new javax.swing.JLabel();
        ComboCultivo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Registro de Producción");

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel10.setText("ID:");

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel11.setText("Fecha:");

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel13.setText("Cantidad:");

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel14.setText("Calidad:");

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel15.setText("Destino:");

        btnagregar.setBackground(new java.awt.Color(102, 255, 102));
        btnagregar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btnagregar.setForeground(new java.awt.Color(255, 255, 255));
        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btnactualizar.setBackground(new java.awt.Color(0, 102, 204));
        btnactualizar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btnactualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btneliminar.setBackground(new java.awt.Color(255, 51, 51));
        btneliminar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnlistarporFecha.setBackground(new java.awt.Color(255, 102, 51));
        btnlistarporFecha.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btnlistarporFecha.setForeground(new java.awt.Color(255, 255, 255));
        btnlistarporFecha.setText("ListarPorfecha");
        btnlistarporFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistarporFechaActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(153, 51, 255));
        btnSalir.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        btnVerTabla.setBackground(new java.awt.Color(255, 255, 153));
        btnVerTabla.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btnVerTabla.setText("Ver Tabla");
        btnVerTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTablaActionPerformed(evt);
            }
        });

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnGenerar.setBackground(new java.awt.Color(102, 102, 102));
        btnGenerar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btnGenerar.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerar.setText("GenerarReporte");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtCultivo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtCultivo.setText("Cultivo");

        ComboCultivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnagregar)
                                .addGap(18, 18, 18)
                                .addComponent(btnactualizar)
                                .addGap(18, 18, 18)
                                .addComponent(btneliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnlistarporFecha)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalir))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox1, 0, 120, Short.MAX_VALUE)
                                    .addComponent(jTextField4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtCultivo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(80, 80, 80)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(jTextField1)
                                    .addComponent(ComboCultivo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField2)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btnGenerar)
                        .addGap(70, 70, 70)
                        .addComponent(btnVerTabla)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ComboCultivo, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addComponent(txtCultivo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addComponent(jLabel15))
                .addGap(129, 129, 129)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnagregar)
                    .addComponent(btnactualizar)
                    .addComponent(btneliminar)
                    .addComponent(btnlistarporFecha)
                    .addComponent(btnSalir))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerTabla)
                    .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed

    try {
     
        String fechaTxt = jFormattedTextField1.getText().trim();
        if (fechaTxt.isEmpty() || fechaTxt.contains("_")) {
            JOptionPane.showMessageDialog(this, "Ingrese una fecha válida (YYYY-MM-DD)");
            return;
        }
        java.sql.Date fecha = java.sql.Date.valueOf(fechaTxt);

        String cantTxt = jTextField2.getText().trim();
        if (cantTxt.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese la cantidad recolectada");
            return;
        }
        double cantidad = Double.parseDouble(cantTxt);

        String calidad = jTextField4.getText().trim();
        if (calidad.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese la calidad");
            return;
        }

        if (ComboCultivo.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un cultivo");
            return;
        }
        String seleccionado = ComboCultivo.getSelectedItem().toString();
        int idCultivo = Integer.parseInt(seleccionado.split(" - ")[0]);

        if (jComboBox1.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un destino");
            return;
        }
        String destinoStr = jComboBox1.getSelectedItem().toString();
        Destino destino = Destino.valueOf(destinoStr);

       
        boolean exito = controller.registrarProduccion(fecha, cantidad, calidad, destino, idCultivo);

        if (exito) {
            JOptionPane.showMessageDialog(this, "¡Producción registrada correctamente!");
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo registrar. Verifique que el cultivo exista.");
        }

    } catch (IllegalArgumentException ex) {
        JOptionPane.showMessageDialog(this, "Destino inválido. Elija uno de la lista.");
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, 
            "ERROR DETALLADO:\n" + e.getMessage(), 
            "Error al guardar", JOptionPane.ERROR_MESSAGE);
    }




    }//GEN-LAST:event_btnagregarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
      try {

        int id = Integer.parseInt(jTextField1.getText().trim());
        Date fecha = Date.valueOf(jFormattedTextField1.getText().trim());
        double cantidad = Double.parseDouble(jTextField2.getText().trim());
        String calidad = jTextField4.getText().trim();
        String destino = jComboBox1.getSelectedItem().toString().trim();

        String item = ComboCultivo.getSelectedItem().toString();
        int idCultivo = Integer.parseInt(item.split(" - ")[0]);

        ProduccionDTO dto = new ProduccionDTO();
        dto.setId(id);
        dto.setFecha(fecha);
        dto.setCantidadRecolectada(cantidad);
        dto.setCalidad(calidad);
        dto.setDestino(destino);
        dto.setIdCultivo(idCultivo);

        if (controller.actualizarProduccion(dto)) {
            JOptionPane.showMessageDialog(this, "Actualizado correctamente.");
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró el registro.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage());
}


    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
       try {
        if (jTextField1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un ID para eliminar.");
            return;
        }

        int id = Integer.parseInt(jTextField1.getText().trim());

        int op = JOptionPane.showConfirmDialog(
            this, 
            "¿Desea eliminar este registro?", 
            "Confirmación", 
            JOptionPane.YES_NO_OPTION
        );

        if (op == JOptionPane.YES_OPTION) {
            if (controller.eliminarProduccion(id)) {
                JOptionPane.showMessageDialog(this, "Registro eliminado correctamente.");
            } else {
                JOptionPane.showMessageDialog(this, "No existe un registro con ese ID.");
            }
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El ID debe ser un número.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
}



    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnlistarporFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistarporFechaActionPerformed
    FrmListarPorFecha ventana = new FrmListarPorFecha();
    ventana.setLocationRelativeTo(null);
    ventana.setVisible(true);
    }//GEN-LAST:event_btnlistarporFechaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
      FrmInicio inicio = new FrmInicio(this.username, this.rol);
    inicio.setLocationRelativeTo(null);
    inicio.setVisible(true);
    this.dispose();


    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnVerTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTablaActionPerformed
       FrmListaProduccion ventana = new FrmListaProduccion();
       ventana.setVisible(true);    
    }//GEN-LAST:event_btnVerTablaActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
       FrmReporteXML ventana = new FrmReporteXML();
       ventana.setLocationRelativeTo(null);
       ventana.setVisible(true);
    }//GEN-LAST:event_btnGenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProduccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboCultivo;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerTabla;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnlistarporFecha;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel txtCultivo;
    // End of variables declaration//GEN-END:variables
}
